#!/usr/bin/env python3
"""Generate rung2_smoke.h: a toolchain-free smoke test for the PULP cluster tile.

Validation-ladder rung 2 (see pulp_esp_integration_report.md): the host loads this
tiny hand-assembled RV32I program into the ESP DMA buffer; every cluster core
executes it from the boot address (L2 window base + 0x8080):

    1. store the 32-bit magic twice (one full 64-bit word) at L2WIN + DATA_OFFS
       - exercises core store -> per2axi -> local xbar -> axi2dmafifo -> ESP DMA write
    2. write 1 to the cluster-control-unit EoC register (cluster periph + 0x000)
       - raises eoc_o -> cluster_control -> acc_done -> ESP STATUS done
    3. spin forever

The instruction fetches themselves exercise i-cache refills through the same
AXI-to-DMA path. All eight cores run the same code; the stores race benignly
(same value, same address).

No PULP toolchain, no pulp-runtime: instructions are encoded here (plain RV32I,
a strict subset of the RI5CY core's ISA). Header format matches
cluster_test_generator/generate_padded_stimuli.py: Stimulus{address,instruction},
BASE_ADDRESS, NUM_STIMULI, with 64-bit words at 8-byte-aligned addresses.

Regenerate with: python3 gen_rung2_stimuli.py > rung2_smoke.h
"""

L2_BASE     = 0xA0103680   # == wrapper L2BaseAddr == translator BASE_ADDR (checked by scripts/check_constants.sh)
BOOT_OFFSET = 0x8080       # == default of the boot_offset user register
CLUSTER_CTRL= 0x50200000   # cluster peripherals base (EoC register at +0x000)
DATA_OFFS   = 0x9000       # where the magic lands, well clear of the code
MAGIC       = 0xCAFEF00D

def lui(rd, imm20):        return ((imm20 & 0xFFFFF) << 12) | (rd << 7) | 0x37
def addi(rd, rs1, imm12):  return ((imm12 & 0xFFF) << 20) | (rs1 << 15) | (0 << 12) | (rd << 7) | 0x13
def sw(rs2, imm12, rs1):
    imm = imm12 & 0xFFF
    return ((imm >> 5) << 25) | (rs2 << 20) | (rs1 << 15) | (2 << 12) | ((imm & 0x1F) << 7) | 0x23
def jal0():                return 0x0000006F  # jal x0, 0 : spin in place

def hi20(addr): return (addr + 0x800) >> 12  # lui/addi pair with sign compensation
def lo12(addr): return addr & 0xFFF

target = L2_BASE + DATA_OFFS
prog = [
    lui (5, hi20(target)),          # x5 = target (hi)
    addi(5, 5, lo12(target)),       #      + lo
    lui (6, hi20(MAGIC)),           # x6 = MAGIC
    addi(6, 6, lo12(MAGIC)),
    sw  (6, 0, 5),                  # [target+0] = MAGIC
    sw  (6, 4, 5),                  # [target+4] = MAGIC  (full 64-bit word)
    lui (7, hi20(CLUSTER_CTRL)),    # x7 = cluster ctrl base
    addi(7, 7, lo12(CLUSTER_CTRL)),
    addi(8, 0, 1),                  # x8 = 1
    sw  (8, 0, 7),                  # EoC register = 1 -> eoc_o
    jal0(),                         # spin
]
# pad the code region with spin instructions so i-cache line refills around the
# program always fetch valid words (line/burst size margin: 128 bytes)
while len(prog) % 32 != 0:
    prog.append(jal0())

entry = L2_BASE + BOOT_OFFSET
stimuli = []
for i in range(0, len(prog), 2):
    lo = prog[i]
    hi = prog[i+1] if i + 1 < len(prog) else jal0()
    stimuli.append((entry + i * 4, (hi << 32) | lo))   # little-endian: low word first
# the magic's target word, zero-initialised (host check expects the overwrite)
stimuli.append((target, 0))

print("// generated by gen_rung2_stimuli.py - do not edit by hand")
print("#ifndef STIMULI_H")
print("#define STIMULI_H")
print("#include <stdint.h>")
print("typedef struct { uint64_t address; uint64_t instruction; } Stimulus;")
print("static const Stimulus stimuli[] = {")
for addr, word in stimuli:
    print("    {0x%08X, 0x%016X}," % (addr, word))
print("};")
print("#define BASE_ADDRESS 0x%08X" % L2_BASE)
print("#define NUM_STIMULI %d" % len(stimuli))
print("#define RUNG2_CHECK_OFFSET 0x%08X  /* byte offset of the magic word in the buffer */" % DATA_OFFS)
print("#define RUNG2_MAGIC64 0x%016XULL" % ((MAGIC << 32) | MAGIC))
print("#endif")
