// axi2dmafifo: AXI4-slave to ESP latency-insensitive DMA protocol translator.
//
// Reworked port of the reference implementation
// (esp_first_pulp_integration/accelerators/rtl/pulp_rtl/rtl/axi2dmafifo.sv) fixing
// the nine defects catalogued in the integration plan (see
// pulp_esp_integration_report.md §4 for the defect-by-defect table):
//
//   - requests are queued in a FIFO (AW/AR always acceptable while space remains),
//     but exactly ONE transaction is outstanding toward the ESP socket at any time
//     (the socket's esp_acc_dma serves one DMA transfer at a time);
//   - AXI addresses are rebased against BASE_ADDR (the cluster-visible L2 window
//     base): ESP DMA index = (addr - BASE_ADDR) >> 3 in 64-bit beats;
//   - full-width (8-byte) reads/writes of any burst length stream straight through;
//   - sub-word (1/2/4-byte) single-beat writes do DMA read-modify-write so the
//     neighbouring bytes of the 64-bit word are preserved (strobe-driven merge,
//     one generic path for all three sizes);
//   - sub-word reads return the full 64-bit word (AXI lane semantics: the master
//     samples its addressed lanes; all lanes carry correct data);
//   - unsupported requests (WRAP bursts, multi-beat narrow bursts, addresses below
//     the window base) are NOT forwarded to the DMA: they drain the AXI channels
//     and complete with SLVERR instead of hanging the FSM.
//
// Contract (guarded by assertions, simulation only):
//   - full-width write beats must have all strobes set (cluster masters honour
//     this: per2axi issues narrow AxSIZE for sub-word stores, mchan and the
//     i-cache issue full-width bursts);
//   - narrow (size<3) transactions are single-beat (len==0), as generated by
//     per2axi.

module axi2dmafifo #(
    parameter int unsigned AXI_ADDR_WIDTH = 32,
    parameter int unsigned AXI_DATA_WIDTH = 64,
    parameter int unsigned AXI_ID_WIDTH   = 4,
    parameter int unsigned AXI_USER_WIDTH = 8,
    parameter int unsigned FIFO_DEPTH     = 4,
    // Base of the cluster-visible L2/DRAM window: subtracted from every AXI address
    // to form the ESP DMA index space (index 0 == first 64-bit word of the
    // accelerator's virtual buffer). Must match the wrapper's xbar rule and the
    // software BASE_ADDRESS (four-constant invariant, plan risk R7).
    parameter logic [31:0] BASE_ADDR      = 32'hA0103680
) (
    input  logic clk,
    input  logic rst_ni,

    // Cluster side (slave of the cluster's AXI master, after the local xbar)
    AXI_BUS.Slave axi_s,

    // ESP socket side: DMA read control/channel
    output logic        dma_read_ctrl_valid,
    output logic [31:0] dma_read_ctrl_data_index,
    output logic [31:0] dma_read_ctrl_data_length,
    output logic [2:0]  dma_read_ctrl_data_size,
    input  logic        dma_read_ctrl_ready,

    input  logic                      dma_read_chnl_valid,
    input  logic [AXI_DATA_WIDTH-1:0] dma_read_chnl_data,
    output logic                      dma_read_chnl_ready,

    // ESP socket side: DMA write control/channel
    output logic        dma_write_ctrl_valid,
    output logic [31:0] dma_write_ctrl_data_index,
    output logic [31:0] dma_write_ctrl_data_length,
    output logic [2:0]  dma_write_ctrl_data_size,
    input  logic        dma_write_ctrl_ready,

    output logic                      dma_write_chnl_valid,
    output logic [AXI_DATA_WIDTH-1:0] dma_write_chnl_data,
    input  logic                      dma_write_chnl_ready
);

  localparam int unsigned StrbWidth = AXI_DATA_WIDTH/8;
  localparam logic [2:0]  SizeDword = 3'b011;   // 8-byte beats (== ESP HSIZE_DWORD)
  localparam logic [1:0]  BurstFixed = 2'b00, BurstIncr = 2'b01, BurstWrap = 2'b10;

  // ---------------------------------------------------------------------------
  // Pending-request FIFO
  // ---------------------------------------------------------------------------
  typedef struct packed {
    logic                      is_write;
    logic [AXI_ID_WIDTH-1:0]   id;
    logic [AXI_USER_WIDTH-1:0] user;    // (defect 8: was AXI_USER_WIDTH+1 bits)
    logic [AXI_ADDR_WIDTH-1:0] addr;    // rebased: axi addr - BASE_ADDR
    logic [7:0]                len;     // AXI beats-1
    logic [2:0]                size;
    logic                      err;     // unsupported request: drain + SLVERR
  } transaction_t;

  transaction_t                    fifo_mem [FIFO_DEPTH];
  logic [$clog2(FIFO_DEPTH)-1:0]   wr_ptr, rd_ptr;
  logic [$clog2(FIFO_DEPTH):0]     count;
  logic [1:0]                      push_n;
  logic                            pop;

  // A request is unsupported when it cannot be mapped onto a single ESP DMA
  // transfer with correct data on every beat (see header).
  function automatic logic req_err(input logic [AXI_ADDR_WIDTH-1:0] addr,
                                   input logic [7:0] len,
                                   input logic [2:0] size,
                                   input logic [1:0] burst);
    logic bad_burst  = (burst == BurstWrap) || ((burst == BurstFixed) && (len != 0));
    logic bad_narrow = (size != SizeDword) && (len != 0);
    logic bad_size   = (size > SizeDword);
    logic bad_window = (addr < BASE_ADDR);
    return bad_burst | bad_narrow | bad_size | bad_window;
  endfunction

  // Acceptance: AW has priority when only one slot is free (defect 5: the
  // reference completed both handshakes and silently dropped both requests).
  localparam logic [$clog2(FIFO_DEPTH):0] DepthCnt = FIFO_DEPTH[$clog2(FIFO_DEPTH):0];
  logic [$clog2(FIFO_DEPTH):0] slots_free;
  assign slots_free   = DepthCnt - count;
  assign axi_s.aw_ready = (slots_free != 0);
  assign axi_s.ar_ready = (slots_free > 1) || ((slots_free == 1) && !axi_s.aw_valid);

  wire aw_hs = axi_s.aw_valid && axi_s.aw_ready;
  wire ar_hs = axi_s.ar_valid && axi_s.ar_ready;

  transaction_t aw_entry, ar_entry;
  assign aw_entry = '{
    is_write: 1'b1,
    id:   axi_s.aw_id,
    user: axi_s.aw_user,
    addr: axi_s.aw_addr - BASE_ADDR,
    len:  axi_s.aw_len,
    size: axi_s.aw_size,
    err:  req_err(axi_s.aw_addr, axi_s.aw_len, axi_s.aw_size, axi_s.aw_burst)
  };
  assign ar_entry = '{
    is_write: 1'b0,
    id:   axi_s.ar_id,
    user: axi_s.ar_user,
    addr: axi_s.ar_addr - BASE_ADDR,
    len:  axi_s.ar_len,
    size: axi_s.ar_size,
    err:  req_err(axi_s.ar_addr, axi_s.ar_len, axi_s.ar_size, axi_s.ar_burst)
  };

  assign push_n = {1'b0, aw_hs} + {1'b0, ar_hs};

  always_ff @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) begin
      wr_ptr <= '0;
      rd_ptr <= '0;
      count  <= '0;
    end else begin
      if (aw_hs && ar_hs) begin
        fifo_mem[wr_ptr] <= aw_entry;
        fifo_mem[(wr_ptr + 1) % FIFO_DEPTH] <= ar_entry;
        wr_ptr <= (wr_ptr + 2) % FIFO_DEPTH;
      end else if (aw_hs) begin
        fifo_mem[wr_ptr] <= aw_entry;
        wr_ptr <= (wr_ptr + 1) % FIFO_DEPTH;
      end else if (ar_hs) begin
        fifo_mem[wr_ptr] <= ar_entry;
        wr_ptr <= (wr_ptr + 1) % FIFO_DEPTH;
      end
      if (pop) rd_ptr <= (rd_ptr + 1) % FIFO_DEPTH;
      count <= count + push_n - {1'b0, pop};   // (defect 7: flags were 1 cycle stale)
    end
  end

  wire          head_valid = (count != 0);
  transaction_t head;
  assign head = fifo_mem[rd_ptr];

  // ---------------------------------------------------------------------------
  // FSM: one transaction at a time toward the ESP socket
  // ---------------------------------------------------------------------------
  typedef enum logic [3:0] {
    IDLE,
    RD_DATA,        // full-width read streaming (any size; lane-correct)
    WR_DATA,        // full-width write streaming
    RMW_RD,         // sub-word write, phase 1: DMA read of the target word
    RMW_WR_CTRL,    // sub-word write, phase 2: issue DMA write control
    RMW_WR_DATA,    // sub-word write, phase 3: strobe-merge and write back
    RESP,           // B channel response
    ERR_RD,         // unsupported read: emit len+1 SLVERR beats, no DMA
    ERR_WR          // unsupported write: drain W beats, then SLVERR response
  } state_t;

  state_t state_q, state_d;
  logic [7:0]                  beat_q, beat_d;
  logic [AXI_DATA_WIDTH-1:0]   aux_q, aux_d;   // old memory word for the RMW merge

  always_ff @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) begin
      state_q <= IDLE;
      beat_q  <= '0;
      aux_q   <= '0;
    end else begin
      state_q <= state_d;
      beat_q  <= beat_d;
      aux_q   <= aux_d;
    end
  end

  always_comb begin
    state_d = state_q;
    beat_d  = beat_q;
    aux_d   = aux_q;
    pop     = 1'b0;

    dma_read_ctrl_valid        = 1'b0;
    dma_read_ctrl_data_index   = '0;
    dma_read_ctrl_data_length  = '0;
    dma_read_ctrl_data_size    = SizeDword;
    dma_read_chnl_ready        = 1'b0;
    dma_write_ctrl_valid       = 1'b0;
    dma_write_ctrl_data_index  = '0;
    dma_write_ctrl_data_length = '0;
    dma_write_ctrl_data_size   = SizeDword;
    dma_write_chnl_valid       = 1'b0;
    dma_write_chnl_data        = '0;

    axi_s.w_ready  = 1'b0;
    axi_s.b_valid  = 1'b0;
    axi_s.b_id     = head.id;
    axi_s.b_user   = head.user;
    axi_s.b_resp   = 2'b00;
    axi_s.r_valid  = 1'b0;
    axi_s.r_data   = '0;
    axi_s.r_id     = head.id;
    axi_s.r_user   = head.user;
    axi_s.r_resp   = 2'b00;
    axi_s.r_last   = 1'b0;

    unique case (state_q)

      IDLE: begin
        beat_d = '0;
        if (head_valid) begin
          if (head.err) begin
            state_d = head.is_write ? ERR_WR : ERR_RD;
          end else if (!head.is_write) begin
            // Any read: fetch len+1 full-width words; the AXI master samples the
            // lanes it addressed (single-beat guaranteed for narrow, see req_err).
            dma_read_ctrl_valid       = 1'b1;
            dma_read_ctrl_data_index  = head.addr >> 3;
            dma_read_ctrl_data_length = head.len + 1;
            if (dma_read_ctrl_ready) state_d = RD_DATA;
          end else if (head.size == SizeDword) begin
            dma_write_ctrl_valid       = 1'b1;
            dma_write_ctrl_data_index  = head.addr >> 3;
            dma_write_ctrl_data_length = head.len + 1;
            if (dma_write_ctrl_ready) state_d = WR_DATA;
          end else begin
            // Sub-word write: read-modify-write (single beat by construction)
            dma_read_ctrl_valid       = 1'b1;
            dma_read_ctrl_data_index  = head.addr >> 3;
            dma_read_ctrl_data_length = 32'd1;
            if (dma_read_ctrl_ready) state_d = RMW_RD;
          end
        end
      end

      RD_DATA: begin
        dma_read_chnl_ready = axi_s.r_ready;
        axi_s.r_valid       = dma_read_chnl_valid;
        axi_s.r_data        = dma_read_chnl_data;
        axi_s.r_last        = (beat_q == head.len);
        if (dma_read_chnl_valid && axi_s.r_ready) begin
          if (beat_q == head.len) begin
            pop     = 1'b1;
            state_d = IDLE;
          end else begin
            beat_d = beat_q + 1;
          end
        end
      end

      WR_DATA: begin
        axi_s.w_ready        = dma_write_chnl_ready;
        dma_write_chnl_valid = axi_s.w_valid;
        dma_write_chnl_data  = axi_s.w_data;
        if (axi_s.w_valid && dma_write_chnl_ready) begin
          if (axi_s.w_last) state_d = RESP;
          else              beat_d  = beat_q + 1;
        end
      end

      RMW_RD: begin
        dma_read_chnl_ready = 1'b1;
        if (dma_read_chnl_valid) begin
          aux_d   = dma_read_chnl_data;
          state_d = RMW_WR_CTRL;
        end
      end

      RMW_WR_CTRL: begin
        dma_write_ctrl_valid       = 1'b1;
        dma_write_ctrl_data_index  = head.addr >> 3;
        dma_write_ctrl_data_length = 32'd1;
        if (dma_write_ctrl_ready) state_d = RMW_WR_DATA;
      end

      RMW_WR_DATA: begin
        axi_s.w_ready        = dma_write_chnl_ready;
        dma_write_chnl_valid = axi_s.w_valid;
        for (int i = 0; i < StrbWidth; i++) begin
          dma_write_chnl_data[i*8 +: 8] =
            axi_s.w_strb[i] ? axi_s.w_data[i*8 +: 8] : aux_q[i*8 +: 8];
        end
        if (axi_s.w_valid && dma_write_chnl_ready) state_d = RESP;
      end

      RESP: begin
        axi_s.b_valid = 1'b1;
        axi_s.b_resp  = head.err ? 2'b10 : 2'b00;  // SLVERR : OKAY
        if (axi_s.b_ready) begin
          pop     = 1'b1;
          state_d = IDLE;
        end
      end

      ERR_RD: begin
        axi_s.r_valid = 1'b1;
        axi_s.r_resp  = 2'b10;                     // SLVERR
        axi_s.r_last  = (beat_q == head.len);
        if (axi_s.r_ready) begin
          if (beat_q == head.len) begin
            pop     = 1'b1;
            state_d = IDLE;
          end else begin
            beat_d = beat_q + 1;
          end
        end
      end

      ERR_WR: begin
        axi_s.w_ready = 1'b1;
        if (axi_s.w_valid && axi_s.w_last) state_d = RESP;
      end

      default: state_d = IDLE;
    endcase
  end

`ifndef SYNTHESIS
  // Contract checks (see header). Violations mean a cluster master emitted
  // traffic this bridge would have silently corrupted in the reference version.
  always_ff @(posedge clk) begin
    if (rst_ni) begin
      if (state_q == WR_DATA && axi_s.w_valid) begin
        assert (&axi_s.w_strb)
          else $error("axi2dmafifo: partial strobes 0x%h on full-width write (addr rebased 0x%h)",
                      axi_s.w_strb, head.addr);
      end
      if (aw_hs) begin
        assert (!aw_entry.err)
          else $warning("axi2dmafifo: unsupported AW (addr 0x%h len %0d size %0d burst %0d) -> SLVERR",
                        axi_s.aw_addr, axi_s.aw_len, axi_s.aw_size, axi_s.aw_burst);
      end
      if (ar_hs) begin
        assert (!ar_entry.err)
          else $warning("axi2dmafifo: unsupported AR (addr 0x%h len %0d size %0d burst %0d) -> SLVERR",
                        axi_s.ar_addr, axi_s.ar_len, axi_s.ar_size, axi_s.ar_burst);
      end
    end
  end
`endif

endmodule
